### ISSUE TITLE
Prediction of numerical features

### ISSUE THREAD

**Issue by loretoparisi** [uber/ludwig#126]
My yaml file looks like

```yaml
training:
    epochs: 10
    learning_rate: 0.001
    batch_size: 128
    early_stop: 10

input_features:
    -
        name: lyrics
        type: text
        encoder: parallel_cnn
        level: word

output_features:
    -
        name: f1
        type: numerical
    -
        name: f2
        type: numerical
```

so I have two float features f1 and f2 (and so MSE will be used by default as loss) to be predicted over a input text, for which I'm using a `parallel_cnn` at word level.

After few epochs I'm getting a 0 accuracy.

```
╒════════════╤═══════════╤════════════╕
│ combined   │      loss │   accuracy │
╞════════════╪═══════════╪════════════╡
│ train      │ 1121.6427 │     0.0000 │
├────────────┼───────────┼────────────┤
│ vali       │ 1140.5157 │     0.0000 │
├────────────┼───────────┼────────────┤
│ test       │ 1136.8768 │     0.0000 │
╘════════════╧═══════════╧════════════╛
```

I get the same result when using for the input a different encoder like 

```yaml
input_features:
    -
        name: lyrics
        type: text
        encoder: rnn
        cell: lstm
        bidirectional: true
```

is the yaml `output_features` definition correct for these float values?
