### ISSUE TITLE
Cannot feed value of shape  for Tensor

### ISSUE THREAD

**Issue by Denniso2** [uber/ludwig#225]
**Describe the bug**
When I try to predict using an image model I trained I get the following error 
`ValueError: Cannot feed value of shape (8,) for Tensor 'Filename/Filename:0', which has shape '(?, 350, 350, 3)'
`
**To Reproduce**
Trying to predict using the command `ludwig predict --data_csv batch/batch.csv -m results/experiment_run_0/model -op`

My yaml is the one below:
```
input_features:
    -
        name: Filename
        type: image
        in_memory: false

output_features:
    -
        name: Rating
        type: numerical

training:
    epochs: 200
    batch_size: 8
    early_stop: 50
```

Example predict data.csv:

```
  | Filename
-- | --
0 | AF336.jpg
1 | AF337.jpg
2 | AF338.jpg
```

Example train data.csv:

```
  | Filename | Rating |  
-- | -- | -- | --
0 | AF1.jpg | 2.33 |  
1 | AF10.jpg | 3.43 |  
2 | AF100.jpg | 2.9 |  
3 | AF1000.jpg | 3.97 |  
4 | AF1001.jpg | 3.73 |  
```

Example image:
![AF343](https://user-images.githubusercontent.com/42325785/54482851-7640ff00-4852-11e9-91c7-7ccf68e5cdaa.jpg)

The images I used to try and predict were some of the training images.They all have dimensions 350x350.

**Environment (please complete the following information):**
 - Latest git version for ludwig
- python 3.7.2
- tensorflow-gpu 1.13.1

Issue seems the same as #100
