### ISSUE TITLE
Experiment with multiple regularization_lambda values

### ISSUE THREAD

**Issue by waelCh** [uber/ludwig#226]
**Description**
I would like to experiemnt the model with different values of `regularization_lambda`
**example**: `regularization_lambda {0.001, 0.01, 0.1}`
How can I do that?

**model_definition.yaml**
```
input_features:
    -
        name: Directories
        type: image
        encoder: stacked_cnn

preprocessing:
    image:
        resize_method: crop_or_pad
        height: 100
        width: 100
        in_memory: true

output_features:
    -
        name: Car_Class
        type: category
        
training:
    batch_size: 32
    num_conv_layers: 10
    regularization_lambda: 0.001
```
