### ISSUE TITLE
most_common_characters text preprocessing parameter doesn't affect anything

### ISSUE THREAD

**Issue by gobzer** [uber/ludwig#232]
Text feature preprocessing parameter `most_common_characters` doesn't seem to work as described in user manual:
https://uber.github.io/ludwig/user_guide/#text-features-preprocessing

**example_data.csv**
```
sometext,cat
"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_.,`!@#$%^&*()<>-+",0
"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_.,`!@#$%^&*()<>-+",1
```

**example_model.yaml**
```
input_features:
    -
        name: sometext
        type: text
        level: char
        preprocessing:
            lowercase: false
            most_common_characters: 75

output_features:
    -
        name: cat
        type: category

preprocessing:
    text:
        lowercase: false
        most_common_characters: 75

training:
    epochs: 1

```

`ludwig experiment -mdf example_model.yaml --data_csv example_data.csv`

vocabulary at **example_data.json** remains 70 chars, while I expect 75

I found that `most_common_characters` doesn't seem to be used at all, but the code uses `char_most_common` instead:
https://github.com/uber/ludwig/blob/8c31e59343a5da52955c1024f71eb9a3862a0cf7/ludwig/features/text_feature.py#L45

`char_most_common` seems to work, but if you'll increase it to like 130:
**example_data2.csv**
```
sometext,cat
"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_.,`!@#$%^&*()<>-+абвгдеёжзийклмнопрстуфхцчшэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧЩЬЪЭЮЯ",0
"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_.,`!@#$%^&*()<>-+абвгдеёжзийклмнопрстуфхцчшэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧЩЬЪЭЮЯ",1
```
**example_model2.yaml**
```
input_features:
    -
        name: sometext
        type: text
        level: char
        preprocessing:
            lowercase: false
            char_most_common: 130

output_features:
    -
        name: cat
        type: category

preprocessing:
    text:
        lowercase: false
        char_most_common: 130

training:
    epochs: 1
```
and run:
`ludwig experiment -mdf example_model2.yaml --data_csv example_data2.csv`
You'll get an InvalidArgumentError (attached)
[char_most_common_130_error_output.txt](https://github.com/uber/ludwig/files/2984272/char_most_common_130_error_output.txt)

Well, I need to increase vocabulary because my data consists of bi-lingual textual data
