### ISSUE TITLE
Number of epochs

### ISSUE THREAD

**Issue by banasu** [uber/ludwig#337]
ludwig train --data_csv DIDK_AllFiles.csv --model_definition "{input_features: [{name: Data, type: numerical}], output_features: [{name: Label, type: category}]}"

I ran ludwig from the terminal and it ran on a 3 class problem with a test accuracy of 25%.
I am not able to change the number of epochs which is default at 100.

Need help. 
![Screenshot from 2019-05-13 15-56-08](https://user-images.githubusercontent.com/24780552/57614368-af69c700-7596-11e9-8f1c-c18e1cb5ecd7.png)

**Comment by carlogrisetti** [comment]
in the model definition you should add a "training:" element, with "epochs: 12345" that states the maximum number of epochs you want to train for. The default value is set to 100 as per https://uber.github.io/ludwig/user_guide/#training

Please also note the "early_stop" parameter, which will stop the training if model is not improved for X epochs, even if "epochs" parameter is set higher. Default value is set to 5

**Comment by msaisumanth** [comment]
```yaml
input_features:
    -
        name: hr_of_day
        type: category

output_features:
    -
        name: rate
        type: numerical

training:
    epochs: 1
```

Example ^
