### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'csv'

### ISSUE THREAD

**Issue by flozi00** [uber/ludwig#349]
**Describe the bug**
I can't predict Images using the Python API.

1. try:

```
df = pd.DataFrame(["/home/developtment/Dokumente/001_0001.jpg"], columns=['img_path'])
pred = model.predict(data_df=df)
```

2. try:
`pred = model.predict(data_csv=os.path.abspath("data.csv"))
`

My definition.yaml:

```
input_features:
    -
        name: img_path
        type: image
        encoder: stacked_cnn
        preprocessing:
            in_memory: false
            height: 75
            width: 75
            num_channels: 3

output_features:
    -
        name: classes
        type: category

training:
    batch_size: 16
    early_stop: 50
```
    

The error:

AttributeError: 'DataFrame' object has no attribute 'csv'

Complete error from python shell:

`File "/home/developtment/Dokumente/app.py", line 24, in predict
    pred = model.predict(data_df=df)
  File "/usr/local/lib/python3.7/dist-packages/ludwig-0.1.2-py3.7.egg/ludwig/api.py", line 812, in predict
    logging_level=logging_level,
  File "/usr/local/lib/python3.7/dist-packages/ludwig-0.1.2-py3.7.egg/ludwig/api.py", line 677, in _predict
    self.model_definition['preprocessing']
  File "/usr/local/lib/python3.7/dist-packages/ludwig-0.1.2-py3.7.egg/ludwig/data/preprocessing.py", line 165, in build_data
    preprocessing_parameters
  File "/usr/local/lib/python3.7/dist-packages/ludwig-0.1.2-py3.7.egg/ludwig/features/image_feature.py", line 227, in add_feature_data
    data_fp = os.path.splitext(dataset_df.csv)[0] + '.hdf5'
  File "/home/developtment/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5067, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'csv'
`

Using the Ludwig cli it works, only with the Python API the error occures.

**Environment (please complete the following information):**
I am using Ubuntu 18 and Python 3 with the newest Version of Ludwig from Master.
