### ISSUE TITLE
Ludwig predicting is giving the same value

### ISSUE THREAD

**Issue by aminaBm** [uber/ludwig#420]
Hello, so this is my YAML file
```
training:

    batch_size: 32
    epochs: 1000
    early_stop: 50
    learning_rate: 0.001
    optimizer:
        type: rmsprop
input_features:
    -
        name: content
        type: sequence
    -
        name: score
        type: category
output_features:
    -
        name: score
        type: numerical
        optimizer:
            type: mean_squared_error
        num_fc_layers: 2
        fc_size: 64
```
Why it's always giving me the same value upper than 1?
for any prediction line in input, it gives me this value = 1.16239...?
how to do to have a value between 0 and 1 and make it more accurate?
