### ISSUE TITLE
Ludwig predicts different value on jupyter notebook kernel restart

### ISSUE THREAD

**Issue by Chee-Foong** [uber/ludwig#421]
**Describe the bug**
Running on Jupyter Notebook.  Ludwig model predicts a different target label each time I restart the kernel even though there is no change to input data, model definition or trained model.  Using fixed default random seed.

** My Code **
````
model = LudwigModel.load('../model/api_experiment_ludwig_3/model')
testdata = pd.read_csv('../data/doc-class-test.csv')

predictions = model.predict(testdata)
model.close()

predictions.to_csv('../output/doc-class-predict.csv', index=False)
````
** My Model Definition **

```
input_features:
    -
        name: person
        type: text
        level: word
        encoder: parallel_cnn
    -
        name: money
        type: text
        level: word
        encoder: parallel_cnn
    -
        name: organisation
        type: text
        level: word
        encoder: parallel_cnn
    -
        name: text
        type: text
        level: word
        encoder: parallel_cnn
    -
        name: w_acceptance
        type: numerical
    -
        name: w_offer
        type: numerical
    -
        name: w_letter
        type: numerical
    -
        name: w_congratulations
        type: numerical
    -
        name: w_invoice
        type: numerical
    -
        name: w_statement
        type: numerical
    -
        name: w_account
        type: numerical
    -
        name: w_total
        type: numerical
    -
        name: w_amount
        type: numerical
    -
        name: w_payable
        type: numerical
    -
        name: n_17
        type: numerical
    -
        name: n_18
        type: numerical
    -
        name: n_19
        type: numerical


output_features:
    -
        name: doctype
        type: category

training:
        epochs: 100  # Default - 100
        batch_size: 128 # Default - 128

```
 
**Expected behavior**
I am expecting a prediction result to be the same given in the inputs and models are the same.

**Environment (please complete the following information):**
 - OS: Ubuntu 16
- Python 3.5.2
- Ludwig 0.1.2

**Additional context**
Let me know if my understanding of Ludwig is not correct.
