### ISSUE TITLE
Import Error: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

### ISSUE THREAD

**Issue by Barathwaja** [uber/ludwig#46]
I'm facing import error while executing the ludwig from google colab.. !!

Below is the code which I **executed in steps**:

1.  Loading Ludwig
   `!pip install ludwig`

2.  Upload file from local to Drive - to use in Colab
    `from google.colab import files`
     `uploaded = files.upload()`
 
3. Train DataSet using ludwig cmd
  `!ludwig train --data_csv ludwig_traindataset_1.csv --model_definition_file model_def.yaml`

My model_def.yaml 

```
input_features:
  - name: utterance
    type: sequence
    encoder: rnn
    cell_type: lstm
    bidirectional: true
    num_layers: 2
    reduce_output: None

output_features:
  - name: intent
    type: category
    reduce_input: sum
    num_fc_layers: 1
    fc_size: 64
  - name: slots
    type: sequence
    decoder: tagger
```

**Dummy Dataset:**

![image](https://user-images.githubusercontent.com/5066436/52621497-72296680-2ecd-11e9-90cb-81240aa4c6bc.png)

**Attached the screenshot error:**

![image](https://user-images.githubusercontent.com/5066436/52621405-31315200-2ecd-11e9-801f-346acefb1cf4.png)

Can anyone help me on this in _Google Colab GPU / Python 3.6_
