### ISSUE TITLE
Example for BERT encoder uses wrong type and crashes

### ISSUE THREAD

**Issue by BeWe11** [uber/ludwig#493]
The documentation for the BERT encoder gives this example of how to set up an encoder using BERT:
```
name: sequence_csv_column_name
type: sequence
encoder: bert
config_path: <path_to_bert_config.json>
checkpoint_path: <path_to_bert_model.ckpt>
do_lower_case: True
preprocessing:
    tokenizer: bert
    vocab_file: <path_to_bert_vocab.txt>
    padding_symbol: '[PAD]'
    unknown_symbol: '[UNK]'
reduce_output: True
```

However, by setting `type: sequence`, training crashes because sequence encoders do not pass the `vocab_file` parameter when creating a vocabulary:
https://github.com/uber/ludwig/blob/71ca2189bcee7a2667c428aeb1bf738697cbe83d/ludwig/features/sequence_feature.py#L76-L80

Compare this to the creation of vocabularies for text encoders:
https://github.com/uber/ludwig/blob/71ca2189bcee7a2667c428aeb1bf738697cbe83d/ludwig/features/text_feature.py#L81-L89

So, either the example should be updated to use `type: text`, or the sequence encoder class should be updated to pass the `vocab_file` parameter to the vocabulary creation.
