### ISSUE TITLE
in_memory: false does not work with images

### ISSUE THREAD

**Issue by tboo** [uber/ludwig#509]
**Describe the bug**
the preprocesing setting `in_memory: false` for images as input features does not seem to work. The hdf5 file is still loaded into the RAM during training.

**To Reproduce**
a .yaml file like this one:

```
input_features:
    -   
        name: image_path
        type: image
        preprocessing:
          in_memory: false
        encoder: stacked_cnn
        conv_layers:
            -   
                num_filters: 32
                filter_size: 15
                pool_size: 2
                pool_stride: 2
            -   
                num_filters: 64
                filter_size: 15
                pool_size: 2
                pool_stride: 2
                dropout: true
        fc_layers:
            -   
                fc_size: 128
                dropout: true



output_features:
    -   
        name: class
        type: category

training:
    reduce_learning_rate_on_plateau: 10
    early_stop: 10
    learning_rate: 0.0004
    batch_size: 40
```

Same is true when I use preprocessing as a separate section at the end of the .yaml file.
