### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by doedelsnj** [uber/ludwig#517]
When i train my model model (with ludwig train -mdf model_definition.yaml --data_csv ./rsna-bone-age/boneage-test-dataset.csv ) ludwig loads my model definition but after finishing it i get "AttributeError: 'NoneType' object has no attribute 'items' ". 
Model Definition data and terminal log are attached.

-Ludwig 0.21
-MacOS 10.14.5
-also tried on google colab

[Archiv.zip](https://github.com/uber/ludwig/files/3617050/Archiv.zip)

[Terminal.txt](https://github.com/uber/ludwig/files/3617066/Terminal.txt)

**Comment by msaisumanth** [comment]
modify your model definition like below:

```yaml
input_features:
    -
        name: id
        type: image
        preprocessing:
                height: 500
                width: 500
                resize_method: interpolate
                scaling: pixel_normalization
                encoder: stacked_cnn

output_features:
    -
        name: sex
        type: category

training:
    
    epochs: 10
    early_stop: 5
```

This should fix the error. In your original model definition, the preprocessing section would be None because it doesn't follow the nested structure required for yaml files. 

Let us know if that solved the issue.
