### ISSUE TITLE
how can i know more detail about my ludwig model?

### ISSUE THREAD

**Issue by Kantshun** [uber/ludwig#558]
after I have trained my ludwig model, how can i know about the structure of my model? for example, if ludwig use a deep neural network, i want to know whether CNN,LSTM,GRU,FCN(fully connected network) is used. sometimes, i want to know the hyperparameter of my model. which file should i look into?

**Comment by manesioz** [comment]
Did you read any of the [documentation](https://uber.github.io/ludwig/)? All of that is specified in the `model_definition.yaml` file. For example: 

```
input_features:
    -
        name: text
        type: text
        level: word
        encoder: parallel_cnn

output_features:
    -
        name: class
        type: category
```
This describes a text classifier which uses a [parallel CNN](https://uber.github.io/ludwig/user_guide/#parallel-cnn-encoder)
