### ISSUE TITLE
Training failure

### ISSUE THREAD

**Issue by tboneai** [uber/ludwig#559]
**Describe the bug**
Used the train and experiment commands but Ludwig stops. Not sure what I am doing wrong. I'm guessing it is yaml related but since it attempts to run I don't believe that is the issue since there are placeholder errors. 

**Update** removed tensorflow2 comment. I verified I am using 1.14 
```
>pip show tensorflow-gpu
Name: tensorflow-gpu
Version: 1.14.0
```
----------------------------------------------------------
[Ludwig output.txt](https://github.com/uber/ludwig/files/3799819/Ludwig.output.txt)
------------------------------------------------------------
```
input_features:
    -
        name: dtstamp
        type: date
        preprocessing: 
                datetime_format: '%Y/%m/%d %H:%M:%S'
    -
        name: open
        type: numerical
    -
        name: high
        type: numerical
    -
        name: low
        type: numerical
    -
        name: close
        type: numerical
output_features:
    -
        name: open
        type: numerical
    -
        name: high
        type: numerical
    -
        name: low
        type: numerical
    -
        name: close
        type: numerical
preprocessing:
        force_split: false
        split_probabilities: [0.7,0.1,0.2]
        stratify: null
        missing_value_strategy: backfill
        encoder: wave
        cell_type: lstm_cudnn
```
------------------------------------------
**Expected behavior**
Expect it to finish training

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 
 - Version [e.g. 22] 1903
- Python version - 3.7
- Ludwig version 

**Additional context**
