### ISSUE TITLE
loss weight is not set to a default value

### ISSUE THREAD

**Issue by lucaventurini** [uber/ludwig#702]
**Describe the bug**

As in title. The bug appears when we set positive_class_weight

**To Reproduce**

The following:

```yaml
    name: MyClass
    type: binary
    loss:
        positive_class_weight: 231.58892815076564
```

throws an exception in:
``File "/usr/local/lib/python3.6/dist-packages/ludwig/features/base_feature.py", line 317, in concat_dependencies_and_build_output
    loss_weight = float(self.loss['weight'])``

This instead works:
```yaml
    name: MyClass
    type: binary
    loss:
        positive_class_weight: 231.58892815076564
        weight: 1
```

**Expected behavior**
loss.weight should be set to a default value?

**Environment (please complete the following information):**
 - OS: Ubuntu
- Python version 3.6
- Ludwig version 0.2.2
