### ISSUE TITLE
Combining 2 input sequences with `sequence` Combiner

### ISSUE THREAD

**Issue by jmizgajski** [uber/ludwig#729]
**Is your feature request related to a problem? Please describe.**
I am trying to figure out how to combine 2 input sequences with `sequence` Combiner and I am not sure if this is possible. It would be great if it would ;) Right now I am getting

```
ValueError: Decoder inputs rank is 2, but should be 3 [batch x sequence x hidden] when using a tagger sequential decoder. Consider setting reduce_output to null / None if a sequential encoder / combiner is used.
```

if I try to put two sequences as inputs to `sequence` combiner.

**Describe the use case**
Consider following (simplified) features where `tag` is the ouput feature.

```
text                                lexicon                                      tag
I am a robot                   0 0 0 1                                      O O O X
George killed Greg        1 0 1                                         X O X
```

**Describe the solution you'd like**
I would like to embed text and lexicon series and predict tag with tagger.
So I would like to set up the combiner in a way that the first row that goes into the encoder of the sequence combiner would look like

```
[ (emb(I) | emb(0)), (emb(am) | emb(0)), (emb(a) | emb(0)), (emb(robot) | emb(1)] 
```

like this:

```
input_features:
  - name: text
    type: text
    level: word
    encoder: embed
    reduce_output: null
  - name: lexicon
    type: sequence
    encoder: embed
    representation: sparse
    reduce_output: null
combiner:
  type: sequence
  main_sequence_feature: text
  encoder: rnn
  cell_type: lstm
  bidirectional: true
  num_layers: 2
  reduce_output: null
output_features:
  - name: tag
    type: sequence
    decoder: tagger
    reduce_inputs: null
```

**Describe alternatives you've considered**
I was hoping for this to work out of the box, but now I am not sure if this is supported.

**Additional context**

**Comment by w4nderlust** [comment]
Your task is exactly the reason why the sequence combiner exists :)

It looks like you did everything correctly apart from `reduce_inputs` in the output feature, which should be `reduce_input`. With that, the tesnor the error is complaining about should have the correct sapes.

Let me know if this fixes your issue. (this also suggests me to provide a mechanism to notify the user when wrong keys are used in the model definition, this would have avoided your error to happen if you got notified).

I am really glad that people are starting to use those more advanced features in Ludwig!

**Comment by jmizgajski** [comment]
Thank you for your fast reply, the promise of an easy way to use those advanced features was what has drawn me to Ludwig in the first place (after seeing you present at Interspeech 2019). 

Unfortunately your recommendation does not solve the problem (same issue persists) - likely because `reduce_input` was set to `None` anyway as it is the default value for `tagger`. 

As to your other points:

I think that ensuring correct user input is an essential addition, as there are few things more frustrating that chasing a configuration typo for half a day ;) You could use something like [jsonschema](https://python-jsonschema.readthedocs.io/en/stable/) for it - it is pretty easy to write and convenient to use for validation. Alternatively [Data Classes in 3.7's PEP 557](https://www.python.org/dev/peps/pep-0557/) could be of use, but maybe its too early for that.

I guess there is also a bug in documentation, as this was a copy-paste from the [tagger definition](https://ludwig-ai.github.io/ludwig-docs/user_guide/#tagger-decoder). Where it says `reduce_inputs` (with the `s` at the end), the same typo appears at least 13 times in the user guide.

**Comment by jmizgajski** [comment]
Also it would be awesome to have a clear example for such a use-case in Examples :)

**Comment by w4nderlust** [comment]
> @w4nderlust Thank you for your fast reply, the promise of an easy way to use those advanced features was what has drawn me to Ludwig in the first place (after seeing you present at Interspeech 2019).

Nice :)

> Unfortunately your recommendation does not solve the problem (same issue persists) - likely because `reduce_input` was set to `None` anyway as it is the default value for `tagger`.

Let me try to fix it. Could you please provide a complete reproducible example with data, configuration and command? The data can be synthetic data generated using the script in `data/dataset_synthesizer.py` and can also be just a couple of lines, no need for the full dataset, as I believe the same problem will appear whith any amount of data.

> As to your other points:
> 
> I think that ensuring correct user input is an essential addition, as there are few things more frustrating that chasing a configuration typo for half a day ;) You could use something like [jsonschema](https://python-jsonschema.readthedocs.io/en/stable/) for it - it is pretty easy to write and convenient to use for validation. Alternatively [Data Classes in 3.7's PEP 557](https://www.python.org/dev/peps/pep-0557/) could be of use, but maybe its too early for that.

These are good suggestions, thank you. Although Ludwig's configuration file is highly dynamic, in the sense that it maps directly the parmeters you put in the configuration to parameters in the classes and functions it uses. For that reason, and for the fact that the classes themselves are often changing and new ones are added, so far I preferred not to have a static parsers for the configuration (it's a v0.x still so I know things will change quite a lot still). Moreover, if a use adds their own additional encoder for instance, they would have to modify the parser too, and I want to avoid that. What I plan to do instead is find a simple mechanism that notifies of all the unrecognized keyowrds passed to each function / object, that could be a temporary solution that preserves dynamicity and avoids failing silently like it happens right now.

> I guess there is also a bug in documentation, as this was a copy-paste from the [tagger definition](https://ludwig-ai.github.io/ludwig-docs/user_guide/#tagger-decoder). Where it says `reduce_inputs` (with the `s` at the end), the same typo appears at least 13 times in the user guide.

Fixed it. Although the default value for sequence features is `sum` not `null`.

> Also it would be awesome to have a clear example for such a use-case in Examples :)

If you agree I can use yours as an example :)

**Comment by jmizgajski** [comment]
this will generate the data
```
import pandas as pd


tagged = {'Greg', 'Xavier', 'Smith', 'Piotr', 'robot', 'dad', 'George'}
lex = {'Greg', 'Xavier', 'robot'}

texts = [
    "I like Greg and Greg likes me more than George",
    "Xavier Smith went to the gym with robot dad",
    "robot dad was not the best dad cause he didn't have limbs",
    "Piotr Smith is a better name than Xavier Greg cause at least it is not both first names",
    "the gut is called the second brain for good reasons listen to your gut",
    "omg how many more examples I have to think of am I a robot or what",
    "this is not going to be easy I should ask my dad for help",
    "well he is busy so here is one more from the top of my head",
    "this is a very nice libary btw i hope we manage to solve this issue so I can continue using it",
    "i have great hopes for it"
]

df = pd.DataFrame(dict(
    text=texts,
    lexicon=[" ".join('1' if w in lex else '0' for w in t.split()) for t in texts],
    tag=[" ".join('X' if w in tagged else 'O' for w in t.split()) for t in texts]  
))
df.to_csv('combiner_test.csv')

```

here is the `example.yaml`

```
input_features:
  - name: text
    type: text
    level: word
    embeddings_trainable: true
    embedding_size: 300
    encoder: embed
    preprocessing:
      word_format: space
    reduce_output: null

  - name: lexicon
    type: sequence
    encoder: embed
    reduce_output: null


combiner:
  type: sequence
  main_sequence_feature: text
  encoder: rnn
  cell_type: lstm
  bidirectional: true
  num_layers: 2
  reduce_input: null
  reduce_output: null

output_features:
  - name: tag
    type: sequence
    decoder: tagger
    reduce_input: null

```

and here is a command to reproduce

```
ludwig train --data_csv combiner_test.csv --model_definition_file example.yaml 

```

**Comment by w4nderlust** [comment]
Thank you, I found the bug and fixed it. Can you please confirm it now works for you?
Please install from master with:
`pip uninstall ludwig & pip install git+http://github.com/uber/ludwig.git`

Also if you confirm your approval, I will add this to both examples and test.

**Comment by jmizgajski** [comment]
I will do that first thing after the Wed meeting spree ;) Thank you @w4nderlust ! :)

You have my approval to use the examples I provided in any way you like, as they are purely synthetic :)

**Comment by jmizgajski** [comment]
@w4nderlust I guess we found another [bug in the docs](https://ludwig-ai.github.io/ludwig-docs/examples/#named-entity-recognition-tagging) then :) as it does say `word_format: space` in the tagger example. (or maybe I am looking at release docs and we changed to work with master throughout the development of this thread, not sure)

also adding these lines under the `text` feature like in the example above did not help, I had to add it as a top level item in the `yaml` file, but now I am able to train. **Thank you!** 

I think this is something to underline in the documentation :)

If any one has the same problem the following config could be of help:
```
input_features:
  - name: text
    type: text
    level: word
    embeddings_trainable: true
    embedding_size: 300
    encoder: embed
    preprocessing:
      word_format: space
    reduce_output: null

  - name: lexicon
    type: sequence
    encoder: embed
    reduce_output: null

combiner:
  type: sequence
  main_sequence_feature: text
  encoder: rnn
  cell_type: lstm
  bidirectional: true
  num_layers: 2
  reduce_input: null
  reduce_output: null

output_features:
  - name: tag
    type: sequence
    decoder: tagger
    reduce_input: null

preprocessing:
  text:
    word_tokenizer: space
```
