### ISSUE TITLE
How do I know what parameters should I specify in encoder?

### ISSUE THREAD

**Issue by pingsutw** [uber/ludwig#736]
For example, when use `stacked_cnn`, I need to specify `num_filters`, `filter_size`, `pool_stride`, ..etc.
Are there any docs that contain 
1. what encoder I could use?
2. what parameters should I specify in that encoder? 
```yaml
input_features:
    -
        name: image_path
        type: image
        encoder: stacked_cnn
        conv_layers:
            -
                num_filters: 32
                filter_size: 3
                pool_size: 2
                pool_stride: 2
            -
                num_filters: 64
                filter_size: 3
                pool_size: 2
                pool_stride: 2
                dropout: true
        fc_layers:
            -
                fc_size: 128
                dropout: true
```
