### ISSUE TITLE
Request: Example Docs showing training configuration 

### ISSUE THREAD

**Issue by ksteinfe** [uber/ludwig#86]
It might save others a bit of time to see an example of specifying training parameters in a YAML file. Took me a bit to figure out the role of dashes in YAML format, and that the training section of the model definition file expects a dictionary, not a list of dictionaries.

As in (note the lack of dashes under the 'training' section):

```
input_features:
  -
    name: image_path
    type: image
    encoder: stacked_cnn
  -
    name: some_number
    type: numerical

output_features:
  -
    name: label
    type: category

training:
    batch_size: 64
```
