### ISSUE TITLE
ludwig train: error: one of the arguments -c/--config -cf/--config_file is required

### ISSUE THREAD

**Issue by aminaBm** [uber/ludwig#988]
command line : `ludwig train --data_csv DataSet.csv --model_definition model_definition.yaml`

my model_definition file :
```
`training:

    batch_size: 32

    epochs: 1000
    early_stop: 50
    learning_rate: 0.001
    optimizer:

        type: rmsprop

input_features:

    -
        name: content
        type: sequence
    -
        name: sarcasm
        type: category
output_features:
    -
        name: score
        type: numerical
        optimizer:
            type: mean_squared_error
        num_fc_layers: 2
        fc_size: 64
`
```
how my dataset looks like 
```
`content,sarcasm,score
she was a perfect Christain girl now you've turned her into a catholic nun! Hahahhahhaha orale ! Hahahha ,non-sarcastic,0`
```

and it shows me this error 
`usage: ludwig train [options]
ludwig train: error: one of the arguments -c/--config -cf/--config_file is required
`
Could someone help me to find out the problem ? :(
